name: build and test

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: > 
          dotnet test
          -p:CollectCoverage=true
          -p:CoverletOutput=TestResults/
          -p:CoverletOutputFormat=opencover
          --configuration Release
          --no-build
          --verbosity normal

      - name: ReSharper annotations
        uses: VMelnalksnis/resharper-inspect-action@v0.2.1
        with:
          solution: VMelnalksnis.ISO20022DotNet.sln

      - name: Gather Code Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
