name: Release

on:
  push:
    branches: [ master ]
    tags: [ v*.*.* ]

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build-artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - VMelnalksnis.ISO20022DotNet

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 6.0.x

      - name: Publish project
        id: publish
        run: >
          deployment/publish.sh
          "${{ matrix.project }}"
          "${{ github.run_number }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ steps.publish.outputs.artifact-name }}
          path: ${{ steps.publish.outputs.artifact }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ steps.publish.outputs.symbols-name }}
          path: ${{ steps.publish.outputs.symbols }}
        
  create-release:
    name: Create release
    needs: build-artifacts
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4.1.3
        id: download
        with:
          path: artifacts

      - name: Create release
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: true
          prerelease: false
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ${{ steps.download.outputs.download-path }}/**/*.nupkg

      - name: NuGet Push
        run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
        working-directory: ${{ steps.download.outputs.download-path }}

      - name: NuGet Push Symboles
        run: dotnet nuget push "**/*.snupkg" --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
        working-directory: ${{ steps.download.outputs.download-path }}
